### ISSUE TITLE
Invalid Physical Devices

### ISSUE THREAD

**Issue by fl0wrian** [thomas-krenn/check_adaptec_raid#4]
Error:
Using arcconf v.2.05.22932 on a Windows 2012r2 Server and the check_adaptec_raid script from https://github.com/thomas-krenn/check_adaptec_raid/pull/3 results in an error 'Invalid physical device(s) specified!' when trying to run "check_adaptec_raid -PD 0".
Same behaviour when using the original script.

When running check_adaptec_raid with defaults and -vvv option the section 'PD' is empty.
Logical Devices seem to work after using the updated script from the pull request.

**Comment by gschoenberger** [comment]
Fix merged. THX a lot!
